objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FN-{000000000}</displayFormat>
        <label>Feedback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Feedback__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/CaseAfterUpdateHandlerTest.cls
@IsTest
public with sharing class CaseAfterUpdateHandlerTest {
    
    @TestSetup
    static void makeData(){
        Case c = new Case(Status = 'New', Origin = 'Web');
        insert c;
    
    }

    @IsTest
    static void testCaseFeedbackCreationPositive(){
        Case c = [SELECT Id, Status FROM Case LIMIT 1];
        c.Status = 'Closed';
        
        Test.startTest();
        update c;
        Test.stopTest();

        List<Feedback__c> feedbackList = [SELECT Id FROM Feedback__c WHERE Case__c =: c.Id];
        Assert.areEqual(1, feedbackList.size(), 'Case updated to Closed but Feedback not created');
    }

    @IsTest
    static void testCaseFeedbackCreationNegative(){

        Case c = [SELECT Id, Status FROM Case LIMIT 1];
        c.Status = 'Working';


        Test.startTest();
        update c;
        Test.stopTest();

        List<Feedback__c> feedbackList = [SELECT Id FROM Feedback__c WHERE Case__c =: c.Id];
        Assert.areEqual(0, feedbackList.size(), 'Feedback should not be created for this case status');

    }
}