objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FN-{000000000}</displayFormat>
        <label>Feedback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Feedback__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Feedback__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Feedback__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Feedback__c/fields/Submitted__c.field-meta.xml
<CustomField>
    <fullName>Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submitted</label>
    <type>Checkbox</type>
</CustomField>

classes/FeedbackUpdateRestTest.cls
@IsTest
private with sharing class FeedbackUpdateRestTest {
    
    @TestSetup
    private static void makeData(){
        Case c = new Case(Status = 'New', Origin = 'Web');
        insert c;
        c.Status = 'Closed';
        update c;
    }

    @IsTest
    private static void testFeedbackUpdateRestSuccessful(){

        Case c = [SELECT Id, CaseNumber FROM Case LIMIT 1];
        String ratingStr = '5';
        String commentsStr = 'Good Support';

        String requestBody = JSON.serialize(new Map<String, Object>{
            'caseNumber' => c.CaseNumber,
            'rating' => ratingStr,
            'comments' => commentsStr
        });

        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/v1/FeedbackUpdate/';
        req.httpMethod = 'PATCH';
        req.requestBody = Blob.valueOf(requestBody);

        RestContext.request = req;
        RestContext.response = new RestResponse();

        Test.startTest();
        String result = FeedbackUpdateRest.updateFeedback();
        Test.stopTest();

        Feedback__c fb = [SELECT Id, Rating__c, Comments__c, Submitted__c FROM Feedback__c WHERE Case__c =: c.Id LIMIT 1];
        Assert.areEqual('Feedback updated successfully', result, 'Feedback did not update');
        Assert.areEqual(ratingStr, fb.Rating__c, 'Feedback rating did not update');
        Assert.areEqual(commentsStr, fb.Comments__c, 'Feedback comments did not update');
        Assert.areEqual(true, fb.Submitted__c, 'Feedback submit field did not update');
        
    }

    @IsTest
    private static void testFeedbackUpdateRestCaseNotFound(){
        
        String ratingStr = '5';
        String commentsStr = 'Good Support';

        String requestBody = JSON.serialize(new Map<String, Object>{
            'caseNumber' => '00100291',
            'rating' => ratingStr,
            'comments' => commentsStr
        });

        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/v1/FeedbackUpdate/';
        req.httpMethod = 'PATCH';
        req.requestBody = Blob.valueOf(requestBody);

        RestContext.request = req;
        RestContext.response = new RestResponse();

        Test.startTest();
        String result = FeedbackUpdateRest.updateFeedback();
        Test.stopTest();

        Assert.areEqual('Bad request', result, 'Case should not exist');

    }

    @IsTest
    private static void testFeedbackUpdateRestCaseNumberBlank(){
        
        String ratingStr = '5';
        String commentsStr = 'Good Support';

        String requestBody = JSON.serialize(new Map<String, Object>{
            'caseNumber' => ' ',
            'rating' => ratingStr,
            'comments' => commentsStr
        });

        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/v1/FeedbackUpdate/';
        req.httpMethod = 'PATCH';
        req.requestBody = Blob.valueOf(requestBody);

        RestContext.request = req;
        RestContext.response = new RestResponse();

        Test.startTest();
        String result = FeedbackUpdateRest.updateFeedback();
        Test.stopTest();

        Assert.areEqual('Invalid Case Number', result, 'Case should not exist');

    }

    @IsTest
    private static void testFeedbackUpdateRestResubmittedFeedback(){

        Case c = [SELECT Id, CaseNumber FROM Case LIMIT 1];
        String ratingStr = '5';
        String commentsStr = 'Good Support';

        String requestBody = JSON.serialize(new Map<String, Object>{
            'caseNumber' => c.CaseNumber,
            'rating' => ratingStr,
            'comments' => commentsStr
        });

        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/v1/FeedbackUpdate/';
        req.httpMethod = 'PATCH';
        req.requestBody = Blob.valueOf(requestBody);

        RestContext.request = req;
        RestContext.response = new RestResponse();

        Test.startTest();
        String result = FeedbackUpdateRest.updateFeedback();
        String result2 = FeedbackUpdateRest.updateFeedback();
        Test.stopTest();

        
        Assert.areEqual('Feedback already submitted', result2, 'Feedback should not be updated');
        
    }

}