objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FN-{000000000}</displayFormat>
        <label>Feedback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Feedback__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Feedback__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Feedback__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Feedback__c/fields/Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Submitted_Date__c</fullName>
    <label>Submitted Date</label>
    <type>Date</type>
</CustomField>

classes/FeedbackCaseLWCSearchController.cls
public with sharing class FeedbackCaseLWCSearchController {
    
    @AuraEnabled(cacheable = true)
    public static List<FeedbackWrapper> searchFeedbacks(String caseNumber){
        try {
            List<Feedback__c> feedbackList = new List<Feedback__c>();
            feedbackList = [select Id, Name, Case__r.CaseNumber, Rating__c, Comments__c, Submitted_Date__c from Feedback__c where Case__r.CaseNumber =: caseNumber ORDER BY LastModifiedDate DESC];

            if(feedbackList.isEmpty()){
                throw new AuraHandledException('No Record Found..');
            }

            List<FeedbackWrapper> feedbackWrapperList = new List<FeedbackWrapper>();
            for(Feedback__c feedbackRec : feedbackList){

                FeedbackWrapper fbWTemp = new FeedbackWrapper();
                fbWTemp.caseNumber = feedbackRec.Case__r.CaseNumber;
                fbWTemp.rating = feedbackRec.Rating__c;
                fbWTemp.comments = feedbackRec.Comments__c;
                fbWTemp.submittedDate = feedbackRec.Submitted_Date__c;
                fbWTemp.name = feedbackRec.Name;
                fbWTemp.Id = feedbackRec.Id;

                feedbackWrapperList.add(fbWTemp);

            }
            return feedbackWrapperList;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class FeedbackWrapper{
        @AuraEnabled public String caseNumber;
        @AuraEnabled public String rating;
        @AuraEnabled public String comments;
        @AuraEnabled public Date submittedDate;
        @AuraEnabled public String name;
        @AuraEnabled public String Id;
    }
}