objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FN-{000000000}</displayFormat>
        <label>Feedback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Feedback__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/CaseAfterUpdateHandler.cls
public with sharing class CaseAfterUpdateHandler {
    public static void caseAfterUpdateHandlerMethod(List<Case> newList, List<Case> oldList, Map<Id, Case> newMap, Map<Id, Case> oldMap) {
        List<Feedback__c> newFeedbacktoInsert = new List<Feedback__c>();

        for(Case c: newList){
            if(c.Status == 'Closed' && oldMap.get(c.Id).Status != 'Closed'){
                Feedback__c fb = new Feedback__c(
                    Case__c = c.Id,
                    OwnerId = c.OwnerId
                );
                newFeedbacktoInsert.add(fb);
            }
        }

        if(!newFeedbacktoInsert.isEmpty()){
            Database.insert(newFeedbacktoInsert, false);
        }
    }
}