objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FN-{000000000}</displayFormat>
        <label>Feedback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Feedback__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Feedback__c/fields/Submitted__c.field-meta.xml
<CustomField>
    <fullName>Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submitted</label>
    <type>Checkbox</type>
</CustomField>

objects/Feedback__c/fields/Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Submitted_Date__c</fullName>
    <label>Submitted Date</label>
    <type>Date</type>
</CustomField>

classes/FeedbackBeforeUpdateHandlerTest.cls
@isTest
public with sharing class FeedbackBeforeUpdateHandlerTest {
    
    @TestSetup
    static void makeData(){
        
        Case c = new Case(Origin = 'Web', Status = 'New');
        insert c;
        c.Status = 'Closed';
        update c;
    }

    @isTest
    static void testFeedbackSubmission(){

        Case c = [SELECT Id, Status FROM Case LIMIT 1];
        Feedback__c fb = [SELECT Id, Submitted__c, Submitted_Date__c FROM Feedback__c WHERE Case__c =: c.Id LIMIT 1];

        Test.startTest();
        fb.Submitted__c = true;
        update fb;
        Test.stopTest();
		
        Feedback__c fbUpdated = [SELECT Id, Submitted_Date__c FROM Feedback__c LIMIT 1];
        Assert.areEqual(Date.today(), fbUpdated.Submitted_Date__c, 'Submitted Date should equal to today');
    
    }
}