objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FN-{000000000}</displayFormat>
        <label>Feedback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Feedback__c/fields/Submitted__c.field-meta.xml
<CustomField>
    <fullName>Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submitted</label>
    <type>Checkbox</type>
</CustomField>

objects/Feedback__c/fields/Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Submitted_Date__c</fullName>
    <label>Submitted Date</label>
    <type>Date</type>
</CustomField>

classes/FeedbackBeforeUpdateHandler.cls
public with sharing class FeedbackBeforeUpdateHandler {
    public static void feedbackBeforeUpdateHandlerMethod(List<Feedback__c> newList, List<Feedback__c> oldList, Map<Id, Feedback__c> newMap, Map<Id, Feedback__c> oldMap){
        for(Feedback__c fb: newList){
            if(fb.Submitted__c && !oldMap.get(fb.Id).Submitted__c && fb.Submitted_Date__c == null){
                fb.Submitted_Date__c = Date.today();
            }
        }
    }
}